### 회원가입 (고객)
POST  http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "1998-01-14",
  "email": "wjddn3751@gmail.com",
  "name": "myName",
  "password": "pw",
  "phone": "01012345678"
}

### 이메일 인증(고객)
GET  http://localhost:8081/signUp/customer/verify?email=wjddn3751@gmail.com&code=

### 로그인 (고객)
POST  http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "wjddn3751@gmail.com",
  "password": "pw"
}

### 회원 정보 조회(고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN:

### 잔액 변경(고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN:

{
  "from": "server",
  "message": "돈 충전",
  "money": 50000
}

########################

### 회원가입 (셀러)
POST  http://localhost:8081/signup/seller
Content-Type: application/json

{
  "birth": "1998-01-14",
  "email": "wjddn3751@gmail.com",
  "name": "myName",
  "password": "pw",
  "phone": "01012345678"
}

### 이메일 인증(고객)
GET  http://localhost:8081/signUp/seller/verify?email=wjddn3751@gmail.com&code=

### 로그인 (셀러)
POST  http://localhost:8081/signin/seler
Content-Type: application/json

{
  "email": "wjddn3751@gmail.com",
  "password": "pw"
}